default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crimebackend_development
  username: karemu200018
  password: mydb
  host: localhost
  port: 5432

test:
  <<: *default
  database: crimebackend_test
  username: karemu200018
  password: mydb
  host: localhost
  port: 5432

production:
  <<: *default
  database: crimebackend_production
  username: karemu200018
  password: <%= ENV["CRIMEBACKEND_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432